name: Release

on:
    push:
        tags:
            - '**'

jobs:

    release:
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'raphaelbudde/jpa2puml' }}

        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: maven
                    server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
                    settings-path: ${{ github.workspace }} # location for the settings.xml file

            -   name: Publish to GitHub Packages Apache Maven
                run: ./mvnw deploy -s $GITHUB_WORKSPACE/settings.xml
                env:
                    GITHUB_TOKEN: ${{ github.token }}
